version: "3.8"

services:
  api:
    image: us-central1-docker.pkg.dev/hydro-dashboard-283320/aes-docker-repo/aes-api:1.0.5
    restart: always
    ports:
      - 8080:8080
    environment:
      PG_ADDRESS: $PG_ADDRESS
      PG_PORT: $PG_PORT
      PG_DATABASE: $PG_DATABASE
      PG_USERNAME: $PG_USERNAME
      PG_PASSWORD: $PG_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgres-db:
    external: false
