version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - $PG_PORT:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USERNAME: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  api:
    image: aes-api
    restart: always
    ports:
      - 8080:8080
    environment:
      PG_ADDRESS: db
      PG_PORT: 5432
      PG_DATABASE: $PG_DATABASE
      PG_USERNAME: $PG_USERNAME
      PG_PASSWORD: $PG_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgres-db:
    external: false
