version: "3.8"

services:
  api:
    image: aes-api
    restart: always
    ports:
      - 80:8080
    environment:
      PG_ADDRESS: $PG_ADDRESS
      PG_PORT: $PG_PORT
      PG_DATABASE: $PG_DATABASE
      PG_USERNAME: $PG_USERNAME
      PG_PASSWORD: $PG_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  postgres-db:
    external: false
