package com.aes.dashboard.backend.service.aesLatestData;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

@SpringBootTest
class AESDataServiceTest {

    @Autowired
    private AESDataService service;

    //@Test
    public void basicTest() {
        List<DataItem> result = service.getLatestData();
        for(DataItem item : result) {
            System.out.println(item.toString());
        }
        Assertions.assertEquals(341, result.size());
    }

    @Test
    public void testAuthTest1() {
        service.refreshAuthToken(
                "77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjksMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWd1ZXN0I2hlcmFsZG92YWxlbnRpQGdtYWlsLmNvbSwwIy5mfG1lbWJlcnNoaXB8dXJuJTNhc3BvJTNhZ3Vlc3QjaGVyYWxkb3ZhbGVudGlAZ21haWwuY29tLDEzMjYxNDE2MzU3MDAwMDAwMCwwLDEzMjYxNjc2NjY5ODYxNzI0NywwLjAuMC4wLDEwMjYsOWY0ZmYyMzktMWNjZS00MjdmLWIyYjktZDNiN2Q0ODUwMmNiLCwsNGFiN2I4OWYtMjBmYi1jMDAwLTAxNzctYjBiYzFkOTFmYmU5LDU4NTAxZDZmLTliOTktNGI3ZC05YzE5LTE0MDU5NzYyZWVjOCxWV1RGTE9RWStVRzhaNXNMcEdkUEN3LDEzMjYxNDE2MDU3MjM3MzU3MiwwLDAsLCwsMjY1MDQ2Nzc0Mzk5OTk5OTk5OSwwLCwsLCwsS0RZZzBnOEhpQzBFZHoycmQwR09lUjVnaHVWYzgzRFJxUHdPL2dEOVZjRkp1T1NJa1loQ2c5QWtvT2M3T1YxV3B2ckdpcGpJZm9VVmJnY3RvTm1iWGZpdEsra0JXVHVkTk1pQmlMaGJSQXdabDFOOWFMbXNQaDYyaThGcDZCY0ZRa0F6SUgrSC9PVVZ0OEIvS1hSSHZqSWkyWlZvTFFqRjBVLzdjTHRtNzBKSGZ0QitIbFdTM0xMRHhEZWgzSDVkaHhwK0NSdFFLVVVNNzl3VGx5SmFsQXpuZFRjUUlMR3Nkc0lmcUc3NDF1TnVHcG5RMEkzRzJOQlQzQ3gwMzJrMExRTmcxM3dqVkdKQTBTMWhjNFpRelpldHl4akVHcGkwMFF5OTRXYkRENEpFdjJKSWxhZ3l0OFFPMlh6WXFQb1dvcm5Eako5c1FOalpVdEZhVGFKRTVBPT08L1NQPg=="
        );
    }

    @Test
    public void testAuthTest2() {
        service.refreshAuthToken(
                "77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjksMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWd1ZXN0I2hlcmFsZG92YWxlbnRpQGdtYWlsLmNvbSwwIy5mfG1lbWJlcnNoaXB8dXJuJTNhc3BvJTNhZ3Vlc3QjaGVyYWxkb3ZhbGVudGlAZ21haWwuY29tLDEzMjYxNDE2MzU3MDAwMDAwMCwwLDEzMjYxNjc2NzU3NjY3NDcyOSwwLjAuMC4wLDEwMjYsOWY0ZmYyMzktMWNjZS00MjdmLWIyYjktZDNiN2Q0ODUwMmNiLCwsNGFiN2I4OWYtMjBmYi1jMDAwLTAxNzctYjBiYzFkOTFmYmU5LGJjMjdjZGI2LTA5ZjQtNGFhYS05MzJmLTUxODFhOTU1ZDRjYyxWV1RGTE9RWStVRzhaNXNMcEdkUEN3LDEzMjYxNDE2MDU3MjM3MzU3MiwwLDAsLCwsMjY1MDQ2Nzc0Mzk5OTk5OTk5OSwwLCwsLCwsbnEvb1V1bE5rYUVyTGZoanRFdEQ2SjhQMlluNzJMOSs2NU1hUFM4RDBvekZrU2NuVzdpelRSNGRkMlBMcXQrT2YreHUxSmgrK05zRWZNamJaUWYxZEV2NC8zWEJhUzVXWlZaNkM2SFNpZ1ExQTRmNEZMMnBDb3RORjZHRXJ4NUk5cnJZS1lrSWI5VGQzRThnL2I5NDA1U3l4U3VRTkRvbm9sUlJOTjd4OHBHV3lTZEZyaDRzNjFrbjE2WjJjMmhpMlB2NU1qMjg1b2JYVkpzSFNVb3JUNTE0aDlZY0xGdkl1NjRJNnJaallDdDRQYTYzekJvK0xOSkxCbm5Eb0NoQ2lULzBSb3R5RE9yMU1tY1IzcXRId3NYZjlneVZWTTlUU3RqR3lKWFo3QW01UWJwZkk3ME5ZOWhaNjhOYUdHK1lIcGFCUlp2SmxNcDZxME5SRFFCSktRPT08L1NQPg=="
        );
    }
    @Test
    public void testAuthTest3() {
        service.refreshAuthToken(
                "77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjksMGguZnxtZW1iZXJzaGlwfHVybiUzYXNwbyUzYWd1ZXN0I2hlcmFsZG92YWxlbnRpQGdtYWlsLmNvbSwwIy5mfG1lbWJlcnNoaXB8dXJuJTNhc3BvJTNhZ3Vlc3QjaGVyYWxkb3ZhbGVudGlAZ21haWwuY29tLDEzMjYxNDE2MzU3MDAwMDAwMCwwLDEzMjYxNjc0MDc5ODc0OTcwNCwwLjAuMC4wLDEwMjYsOWY0ZmYyMzktMWNjZS00MjdmLWIyYjktZDNiN2Q0ODUwMmNiLCwsNGFiN2I4OWYtMjBmYi1jMDAwLTAxNzctYjBiYzFkOTFmYmU5LDEyNjVlZTY3LTRmN2QtNGNlMy1hNzg4LTA0YjhlMjAwMDVjNSxWV1RGTE9RWStVRzhaNXNMcEdkUEN3LDEzMjYxNDE2MDU3MjM3MzU3MiwwLDAsLCwsMjY1MDQ2Nzc0Mzk5OTk5OTk5OSwwLCwsLCwsdEw0UDRMR0ZnYm9UdHB4NitKVHNxVnd1ZnVoeTh6VUVwVEo5cHpVSGFNa2ZLVFhOeTZwT3RCTkFMQXN3RXJ0VHNocjgramF6WVpicWNrWTczT3FiQ3ZzbERxU1JOZUVvcXNQMTJtZHlxMUNobkJWamdyMHN5cVJlaDBza2orajRPbU1KcFYxT25ON21OR2VBdGRpajgyaElURVBMdE1kMnk4MHByZUJ0WW9kOGd6Z1pxRUZwaWxNRzRWb0hBVXhqdjZpZDJIQ0NJNzFSSm0rZUhVMmViUC9nQng2bW9OMmxyeUF5WlJJNUtOSmI4TGdZelRobm5ZbU1LVmRWZjVHbm14RGdSVHZWUHlVcW45U1lqZE5TQkJtT1dHT3gvQ3IwcytneVNuZzdta2JxY2RpSUI2NXBjVU1RZ0JvbG9JQWZKTUVKYlFsQm81cmFyY0poL1BqUVNnPT08L1NQPg=="
        );
    }

}